<a href="https://colab.research.google.com/github/Utomi-Tom/Movie-Binary-classification/blob/main/IMBD_movie_classification_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction on the IMDB review project
The IMDB dataset consist of: a set of 50,000 highly polarized reviews from the
Internet Movie Database. They’re split into 25,000 reviews for training and 25,000
reviews for testing, each set consisting of 50% negative and 50% positive reviews.


Just like the MNIST dataset, the IMDB dataset comes packaged with Keras. It has
already been preprocessed: the reviews (sequences of words) have been turned into
sequences of integers, where each integer stands for a specific word in a dictionary.

# Importing library


The following code will load the dataset (when you run it the first time, about
80 MB of data will be downloaded to your machine).

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
# Import dataset 
(x_tr, y_tr), (x_tt, y_tt) = keras.datasets.imdb.load_data(num_words=10000)

17464789/17464789 [==============================] - 0s 0us/step


The argument *num_words* =10000 means you’ll only keep the top 10,000 most frequently
occurring words in the training data. Rare words will be discarded. This allows
you to work with vector data of manageable size.

In [3]:
word_index = keras.datasets.imdb.get_word_index()

1641221/1641221 [==============================] - 0s 0us/step


Above code is how I quickly decode one of these reviews back to English
words:


*get_word_index* is a dictionary, mapping
words to an integer index.

In [4]:
r_word_ind = dict([(value, key) for (key, value) in word_index.items()])

The above code reverses the mapping process, by mapping
integer indices to words.

In [5]:
decoded_review = "".join([r_word_ind.get(i - 3, "?") for i in x_tr[3]])

In [6]:
decoded_review


"?the??atstorytellingthetraditionalsortmanyyearsaftertheeventicanstillseeinmy?eyeanelderlyladymyfriend'smotherretellingthebattleof?shemakesthecharacterscomealiveherpassionisthatofaneyewitnessonetotheeventsonthe?heathamileorsofromwhereshelivesbrbrofcourseithappenedmanyyearsbeforeshewasbornbutyouwouldn'tguessfromthewayshetellsitthesamestoryistoldinbarsthelengthand?ofscotlandasidiscusseditwithafriendonenightin?alocalcutintogivehisversionthediscussioncontinuedtoclosingtimebrbrstoriespasseddownlikethisbecomepartofourbeingwhodoesn'trememberthestoriesourparentstolduswhenwewerechildrentheybecomeourinvisibleworldandaswegrowoldertheymaybestillserveasinspirationorasanemotional?factandfictionblendwith?rolemodelswarningstories?magicandmysterybrbrmynameis?likemygrandfatherandhisgrandfatherbeforehimourprotagonistintroduceshimselftousandalsointroducesthestorythatstretchesbackthroughgenerationsitproducesstorieswithinstoriesstoriesthatevokethe?wonderofscotlanditsruggedmountains?in?thestuffoflegendyet?is

The variables **x_tr and x_tt** are lists of reviews; each review is a list of
word indices (encoding a sequence of words).**y_tr and y_tt** are
lists of 0s and 1s, where 0 stands for negative and 1 stands for positive:

# Preparing the data

Because I cannot feed lists of integers into a neural network. I need to turn your lists into tensors and there are two ways to do that.


*  Pad your lists so that they all have the same length, turn them into an integer
tensor of shape (samples, word_indices), and then use as the first layer in
your network a layer capable of handling such integer tensors (the Embedding
layer, which we’ll cover in detail later in the book). 
*  One-hot encode your lists to turn them into vectors of 0s and 1s. This would
mean, for instance, turning the sequence [3, 5] into a 10,000-dimensional vector
that would be all 0s except for indices 3 and 5, which would be 1s. Then you
could use as the first layer in your network a Dense layer, capable of handling
floating-point vector data.



Let’s go with the latter solution to vectorize the data, which you’ll do manually for
maximum clarity.


In [8]:
# Encoding the integer sequences into a binary matrix

def vectorize_seq (sequence, dim= 10000):
  results = np.zeros((len(sequence), dim))
  for i, sequence in enumerate(sequence):
    results[i, sequence] = 1
  return results

In [13]:
train_data = vectorize_seq(x_tr)
print(train_data
      )

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [12]:
test_data = vectorize_seq(x_tt)
print(test_data
      )

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [14]:
# Vectorize labels as well

label_train = np.asarray(y_tr).astype("float32")
label_test = np.asarray(y_tt).astype("float32")

Now the data is ready to be fed into a neural network.

# Building your network